site_name: Mohamed Amine CHALHY
site_description: Data Science Master's Student | Machine Learning Engineer
site_author: Mohamed Amine CHALHY
site_url: https://github.com/Mohemed-Amine-Chalhy/portfolio-

theme:
  name: material
  palette:
    # Light mode
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  
  icon:
    repo: fontawesome/brands/github

repo_url: https://github.com/Mohemed-Amine-Chalhy
repo_name: GitHub

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Mohemed-Amine-Chalhy
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/mohamed-amine-chalhy/
    - icon: fontawesome/solid/envelope
      link: mailto:Mohamed.CHALHY@EMINES.UM6P.ma

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Experience: experience.md
  - Projects: projects/
  - Skills: skills.md
  - Contact: contact.md
plugins:
      - mkdocs-jupyter
      - awesome-pages
